all:
	g++ graph.cpp funcgraph.cpp -o graph -g -Wall -Wextra -Wpedantic -Werror -fsanitize=address
build:
	g++ graph.cpp funcgraph.cpp -o graph -g -Wall -Wextra -Wpedantic -Werror -fsanitize=address
clean:
	rm -rf graph tests *.o
tests:
	g++ tests.cpp funcgraph.cpp -o tests -g -Wall -Wextra -Wpedantic -Werror -fsanitize=address
